### PR TITLE
Linting: trailing whitespace

### PR DESCRIPTION
**Pull request by Nathan-Schwartz**
This PR adds adds a linting rule that warns when there is trailing whitespace.

Running `yarn lint:fix` will fix all occurrences.

I do realize this is a personal preference, let me know if you'd prefer to leave it as-is 🙂

### CODE REVIEW

**Comment by WoLfulus** [comment]
It'll be awesome to add a .editorconfig with `trim_trailing_whitespace = true` too. Most IDEs support .editorconfig and you won't need to keep manually fixing those.

http://editorconfig.org/

**Comment by icebob** [comment]
@WoLfulus It added: https://github.com/ice-services/moleculer/blob/master/.editorconfig#L6
But vscode doesn't do it at me. Any idea why?

**Comment by WoLfulus** [comment]
@icebob you should install an extension on vscode to make it work.

**Comment by icebob** [comment]
Thanks. I will merge it after #72

**Comment by Nathan-Schwartz** [comment]
Updated commit to fixed conflicts

**Comment by icebob** [comment]
Thank you! Merged!

**Pull request merged**
