### PR TITLE
Improve AMQP Integration Tests

### PR DESCRIPTION
**Pull request by Nathan-Schwartz**
### Changes
- Remove legacy amqp tests
- Add important test cases for RPC
- Enhance purge function to allow clearing queues without deleting. Clears queues between tests and deletes queues and exchanges before and after suites.
- Fix type error in AMQP Transporter
- Run the same test suite for built-in and AMQP balancing
- preferLocal = false for RPC suite
- Run AMQP integration tests serially to prevent unexpected states

@icebob let me know if you any questions or concerns 👍

### CODE REVIEW

**Comment by icebob** [comment]
Thanks Nathan, I'm checking....

**Comment by icebob** [comment]
I got errors in `rpc.spc.js`:
```
[0m[7m[1m[31m FAIL [39m[22m[27m[0m [2mtest\integration\amqp\[22m[1mrpc.spc.js[22m ([0m[1m[41m81.549s[49m[22m[0m)
[1m[31m  [1m● [1mTest AMQPTransporter › Test AMQPTransporter RPC with built-in balancer › Nodes should only receive one request at a time by default[39m[22m

    [2mexpect([22m[31mreceived[39m[2m).toBe([22m[32mexpected[39m[2m)[22m
    
    Expected value to be (using ===):
      [32m"respond"[39m
    Received:
      [31m"receive"[39m
[2m      
      [2mat logs.forEach ([2m[0m[36mtest/integration/amqp/rpc.spc.js[39m[0m[2m:118:26)[2m
      at Array.forEach (native)
      [2mat Promise.all.then.catch.then.res ([2m[0m[36mtest/integration/amqp/rpc.spc.js[39m[0m[2m:108:9)[2m
      [2mat tryCatcher ([2m[0m[36mnode_modules/bluebird/js/release/util.js[39m[0m[2m:16:23)[2m
      [2mat Promise._settlePromiseFromHandler ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:512:31)[2m
      [2mat Promise._settlePromise ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:569:18)[2m
      [2mat Promise._settlePromise0 ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:614:10)[2m
      [2mat Promise._settlePromises ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:693:18)[2m
      [2mat Promise._fulfill ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:638:18)[2m
      [2mat Promise._settlePromise ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:582:21)[2m
      [2mat Promise._settlePromise0 ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:614:10)[2m
      [2mat Promise._settlePromises ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:693:18)[2m
      [2mat Promise._fulfill ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:638:18)[2m
      [2mat PromiseArray._resolve ([2m[0m[36mnode_modules/bluebird/js/release/promise_array.js[39m[0m[2m:126:19)[2m
      [2mat PromiseArray._promiseFulfilled ([2m[0m[36mnode_modules/bluebird/js/release/promise_array.js[39m[0m[2m:144:14)[2m
      [2mat Promise._settlePromise ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:574:26)[2m[22m

[1m[31m  [1m● [1mTest AMQPTransporter › Test AMQPTransporter RPC with built-in balancer › Should use availability-based load balancing[39m[22m

    [2mexpect([22m[31mreceived[39m[2m).toHaveLength([22m[32mlength[39m[2m)[22m
    
    Expected value to have length:
      [32m1[39m
    Received:
      [31m[{"params": {"delay": 3000}, "timestamp": 1507578787927, "type": "respond", "worker": 2}, {"params": {"delay": 20}, "timestamp": 1507578784946, "type": "respond", "worker": 2}, {"params": {"delay": 20}, "timestamp": 1507578784946, "type": "respond", "worker": 2}][39m
    received.length:
      [31m3[39m
[2m      
      [2mat Promise.all.catch.then.res ([2m[0m[36mtest/integration/amqp/rpc.spc.js[39m[0m[2m:145:53)[2m
      [2mat tryCatcher ([2m[0m[36mnode_modules/bluebird/js/release/util.js[39m[0m[2m:16:23)[2m
      [2mat Promise._settlePromiseFromHandler ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:512:31)[2m
      [2mat Promise._settlePromise ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:569:18)[2m
      [2mat Promise._settlePromise0 ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:614:10)[2m
      [2mat Promise._settlePromises ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:693:18)[2m
      [2mat Promise._fulfill ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:638:18)[2m
      [2mat Promise._settlePromise ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:582:21)[2m
      [2mat Promise._settlePromise0 ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:614:10)[2m
      [2mat Promise._settlePromises ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:693:18)[2m
      [2mat Promise._fulfill ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:638:18)[2m
      [2mat PromiseArray._resolve ([2m[0m[36mnode_modules/bluebird/js/release/promise_array.js[39m[0m[2m:126:19)[2m
      [2mat PromiseArray._promiseFulfilled ([2m[0m[36mnode_modules/bluebird/js/release/promise_array.js[39m[0m[2m:144:14)[2m
      [2mat Promise._settlePromise ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:574:26)[2m
      [2mat Promise._settlePromise0 ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:614:10)[2m
      [2mat Promise._settlePromises ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:693:18)[2m
      [2mat Async.Object.<anonymous>.Async._drainQueue ([2m[0m[36mnode_modules/bluebird/js/release/async.js[39m[0m[2m:133:16)[2m
      [2mat Async.Object.<anonymous>.Async._drainQueues ([2m[0m[36mnode_modules/bluebird/js/release/async.js[39m[0m[2m:143:10)[2m
      [2mat Immediate.Async.drainQueues ([2m[0m[36mnode_modules/bluebird/js/release/async.js[39m[0m[2m:17:14)[2m[22m

[1m[31m  [1m● [1mTest AMQPTransporter › Test AMQPTransporter RPC with built-in balancer › Messages that haven't finished processing should be retryable by other nodes.[39m[22m

    [2mexpect([22m[31mreceived[39m[2m).toHaveLength([22m[32mlength[39m[2m)[22m
    
    Expected value to have length:
      [32m9[39m
    Received:
      [31m[{"params": {"crash": true, "delay": 20}, "timestamp": 1507578790892, "type": "respond", "worker": 1}, {"params": {"crash": true, "delay": 20}, "timestamp": 1507578790892, "type": "respond", "worker": 1}, {"params": {"crash": true, "delay": 20}, "timestamp": 1507578790892, "type": "respond", "worker": 1}][39m
    received.length:
      [31m3[39m
[2m      
      [2mat Promise.all.catch.then.res ([2m[0m[36mtest/integration/amqp/rpc.spc.js[39m[0m[2m:167:51)[2m
      [2mat tryCatcher ([2m[0m[36mnode_modules/bluebird/js/release/util.js[39m[0m[2m:16:23)[2m
      [2mat Promise._settlePromiseFromHandler ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:512:31)[2m
      [2mat Promise._settlePromise ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:569:18)[2m
      [2mat Promise._settlePromise0 ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:614:10)[2m
      [2mat Promise._settlePromises ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:693:18)[2m
      [2mat Promise._fulfill ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:638:18)[2m
      [2mat Promise._settlePromise ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:582:21)[2m
      [2mat Promise._settlePromise0 ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:614:10)[2m
      [2mat Promise._settlePromises ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:693:18)[2m
      [2mat Promise._fulfill ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:638:18)[2m
      [2mat PromiseArray._resolve ([2m[0m[36mnode_modules/bluebird/js/release/promise_array.js[39m[0m[2m:126:19)[2m
      [2mat PromiseArray._promiseFulfilled ([2m[0m[36mnode_modules/bluebird/js/release/promise_array.js[39m[0m[2m:144:14)[2m
      [2mat Promise._settlePromise ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:574:26)[2m
      [2mat Promise._settlePromise0 ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:614:10)[2m
      [2mat Promise._settlePromises ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:693:18)[2m
      [2mat Async.Object.<anonymous>.Async._drainQueue ([2m[0m[36mnode_modules/bluebird/js/release/async.js[39m[0m[2m:133:16)[2m[22m

[1m[31m  [1m● [1mTest AMQPTransporter › Test AMQPTransporter RPC with DISABLED built-in balancer › Should load balance requests to available nodes.[39m[22m

    [2mexpect([22m[31mreceived[39m[2m).toEqual([22m[32mexpected[39m[2m)[22m
    
    Expected value to equal:
      [32m[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3][39m
    Received:
      [31m[1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3][39m
    
    Difference:
    
    [32m- Expected[39m
    [31m+ Received[39m
    
    [2m Array [[22m
    [2m   1,[22m
    [2m   1,[22m
    [2m   1,[22m
    [32m-  1,[39m
    [2m   2,[22m
    [2m   2,[22m
    [2m   2,[22m
    [2m   2,[22m
    [2m   3,[22m
    [2m   3,[22m
    [2m   3,[22m
    [2m   3,[22m
    [31m+  3,[39m
    [2m ][22m
[2m      
      [2mat Promise.all.catch.then.res ([2m[0m[36mtest/integration/amqp/rpc.spc.js[39m[0m[2m:88:42)[2m
      [2mat tryCatcher ([2m[0m[36mnode_modules/bluebird/js/release/util.js[39m[0m[2m:16:23)[2m
      [2mat Promise._settlePromiseFromHandler ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:512:31)[2m
      [2mat Promise._settlePromise ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:569:18)[2m
      [2mat Promise._settlePromise0 ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:614:10)[2m
      [2mat Promise._settlePromises ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:693:18)[2m
      [2mat Promise._fulfill ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:638:18)[2m
      [2mat Promise._settlePromise ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:582:21)[2m
      [2mat Promise._settlePromise0 ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:614:10)[2m
      [2mat Promise._settlePromises ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:693:18)[2m
      [2mat Promise._fulfill ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:638:18)[2m
      [2mat PromiseArray._resolve ([2m[0m[36mnode_modules/bluebird/js/release/promise_array.js[39m[0m[2m:126:19)[2m
      [2mat PromiseArray._promiseFulfilled ([2m[0m[36mnode_modules/bluebird/js/release/promise_array.js[39m[0m[2m:144:14)[2m
      [2mat Promise._settlePromise ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:574:26)[2m
      [2mat Promise._settlePromise0 ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:614:10)[2m
      [2mat Promise._settlePromises ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:693:18)[2m
      [2mat Async.Object.<anonymous>.Async._drainQueue ([2m[0m[36mnode_modules/bluebird/js/release/async.js[39m[0m[2m:133:16)[2m[22m

[1m[31m  [1m● [1mTest AMQPTransporter › Test AMQPTransporter RPC with DISABLED built-in balancer › Should use availability-based load balancing[39m[22m

    [2mexpect([22m[31mreceived[39m[2m).toHaveLength([22m[32mlength[39m[2m)[22m
    
    Expected value to have length:
      [32m1[39m
    Received:
      [31m[{"params": {"delay": 3000}, "timestamp": 1507578806079, "type": "respond", "worker": 2}, {"params": {"delay": 20}, "timestamp": 1507578803098, "type": "respond", "worker": 2}, {"params": {"delay": 20}, "timestamp": 1507578803100, "type": "respond", "worker": 2}][39m
    received.length:
      [31m3[39m
[2m      
      [2mat Promise.all.catch.then.res ([2m[0m[36mtest/integration/amqp/rpc.spc.js[39m[0m[2m:145:53)[2m
      [2mat tryCatcher ([2m[0m[36mnode_modules/bluebird/js/release/util.js[39m[0m[2m:16:23)[2m
      [2mat Promise._settlePromiseFromHandler ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:512:31)[2m
      [2mat Promise._settlePromise ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:569:18)[2m
      [2mat Promise._settlePromise0 ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:614:10)[2m
      [2mat Promise._settlePromises ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:693:18)[2m
      [2mat Promise._fulfill ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:638:18)[2m
      [2mat Promise._settlePromise ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:582:21)[2m
      [2mat Promise._settlePromise0 ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:614:10)[2m
      [2mat Promise._settlePromises ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:693:18)[2m
      [2mat Promise._fulfill ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:638:18)[2m
      [2mat PromiseArray._resolve ([2m[0m[36mnode_modules/bluebird/js/release/promise_array.js[39m[0m[2m:126:19)[2m
      [2mat PromiseArray._promiseFulfilled ([2m[0m[36mnode_modules/bluebird/js/release/promise_array.js[39m[0m[2m:144:14)[2m
      [2mat Promise._settlePromise ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:574:26)[2m
      [2mat Promise._settlePromise0 ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:614:10)[2m
      [2mat Promise._settlePromises ([2m[0m[36mnode_modules/bluebird/js/release/promise.js[39m[0m[2m:693:18)[2m
      [2mat Async.Object.<anonymous>.Async._drainQueue ([2m[0m[36mnode_modules/bluebird/js/release/async.js[39m[0m[2m:133:16)[2m
      [2mat Async.Object.<anonymous>.Async._drainQueues ([2m[0m[36mnode_modules/bluebird/js/release/async.js[39m[0m[2m:143:10)[2m
      [2mat Immediate.Async.drainQueues ([2m[0m[36mnode_modules/bluebird/js/release/async.js[39m[0m[2m:17:14)[2m[22m

[1m[31m  [1m● [1mTest AMQPTransporter › Test AMQPTransporter RPC with DISABLED built-in balancer › Messages that haven't finished processing should be retryable by other nodes.[39m[22m

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
[2m      
      [2mat pTimeout ([2m[0m[36mnode_modules/jest-jasmine2/build/queueRunner.js[39m[0m[2m:53:21)[2m
      [2mat ontimeout ([2m[0m[36mtimers.js[39m[0m[2m:365:14)[2m
      [2mat tryOnTimeout ([2m[0m[36mtimers.js[39m[0m[2m:237:5)[2m
      [2mat Timer.listOnTimeout ([2m[0m[36mtimers.js[39m[0m[2m:207:5)[2m[22m

[0m[7m[1m[32m PASS [39m[22m[27m[0m [2mtest\integration\amqp\[22m[1mbroadcast.spc.js[22m ([0m[1m[41m19.528s[49m[22m[0m)
[0m[7m[1m[32m PASS [39m[22m[27m[0m [2mtest\integration\amqp\[22m[1memit.spc.js[22m ([0m[1m[41m14.901s[49m[22m[0m)
[999D[K
[1mTest Suites: [22m[1m[31m1 failed[39m[22m, [1m[32m2 passed[39m[22m, 3 total
[1mTests:       [22m[1m[31m6 failed[39m[22m, [1m[32m9 passed[39m[22m, 15 total
[1mSnapshots:   [22m0 total
[1mTime:[22m        116.06s
[2mRan all test suites[22m[2m.[22m

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:amqp"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! moleculer@0.11.2 test:amqp: `jest --testMatch "**/integration/amqp/**spc.js" --runInBand`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the moleculer@0.11.2 test:amqp script 'jest --testMatch "**/integration/amqp/**spc.js" --runInBand'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the moleculer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jest --testMatch "**/integration/amqp/**spc.js" --runInBand
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs moleculer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls moleculer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     d:\Work\ice-services\moleculer\npm-debug.log

```

**Comment by Nathan-Schwartz** [comment]
Just made a quick change so purge.js makes new channels instead of new connections.

**Comment by icebob** [comment]
@Nathan-Schwartz so, the rpc test is good, and I need to fix AMQP transporter to test will be passed?

**Comment by Nathan-Schwartz** [comment]
@icebob Yes, I think so.

I would expect these to fail:
screen shot 2017-10-09 at 3 16 52 pm

But sometimes the load balancing one fails, because `ack` happens before the action handler completes.

**Comment by icebob** [comment]
The last 2 test case doesn't work with built-in balancer, only with disabled balancer

**Comment by Nathan-Schwartz** [comment]
@icebob Can you clarify?

Are you saying that you don't want them to work with built-in balancer, or that it doesn't currently?

**Comment by icebob** [comment]
It can't work, because Moleculer balancer put the request to the (i.e.) `MOL.REQ.worker-1` queue. If no ack, RabbitMQ won't move this request to the `MOL.REQ.worker-2` queue.

**Comment by icebob** [comment]
And also availability balancing is working only disabled balancer.
Broker put the request to `*.worker-1`, `*.worker-2`, `*.worker-3`.
But if you disable balancer, broker will put the request to `MOL.REQB.test.hello` queue.

**Comment by Nathan-Schwartz** [comment]
@icebob Ahh, okay. I didn't realize that. Thanks!

I will update the PR.

**Comment by icebob** [comment]
No, I fixed it :)

**Comment by icebob** [comment]
So, your first AMQP implementation was a disabled balancer solution, just I added the built-in balancer solution too.

**Comment by Nathan-Schwartz** [comment]
@icebob That looks really good!

I think maybe you switched `true` and `false` in the describe blocks 🙂

**Comment by icebob** [comment]
Yes, fixed :)
Btw, the test doesn't exit gracefully, maybe missing broker.stop?!?!

**Comment by brad-decker** [comment]
The collaboration on this is amazing. Thanks @Nathan-Schwartz and @icebob !

**Comment by icebob** [comment]
Ohh, the `--runInBand` blocking the exit.

**Comment by icebob** [comment]
@Nathan-Schwartz Do you know how we can use RabbitMQ on Travis CI?

**Comment by Nathan-Schwartz** [comment]
@icebob Ohh interesting. Nice find with `forceExit` 👍 

I haven't set up RabbitMQ with Travis before, but it looks it shouldn't be too hard to configure:
https://docs.travis-ci.com/user/database-setup/#RabbitMQ

**Comment by icebob** [comment]
Great! I'm trying...

**Comment by Nathan-Schwartz** [comment]
🎉

**Comment by icebob** [comment]
Wow, It passed! :tada: :)

**Comment by Nathan-Schwartz** [comment]
Thanks Icebob!

**Comment by icebob** [comment]
Thanks Nathan, good job!

**Comment by icebob** [comment]
Now I have to go, I'm at midnight :) 
I'm going to release a new version tomorrow.

**Comment by icebob** [comment]
I released a new version with this fix.
https://github.com/ice-services/moleculer/releases/tag/v0.11.3

**Pull request merged**
